Adds Particle Network to list of wallets
0xPolygon/wiki pull request #135
Opened 2023-10-06 07:54 UTC by TABASCOatw

Adds Particle Network to list of wallets in `getting-started.md`.

Additionally, this PR adds a page within the wallet section for Particle Network, modeled closely after existing pages in the same section.

2023-10-06 09:52 UTC, DannyS03 requested changes
thanks for the contribution @TABASCOatw, we are reviewing.

In the meantime, do you mind adding the document ID to `sidebars.js`? Would recommend adding it [here](https://github.com/0xPolygon/wiki/blob/main/sidebars.js#L106C15-L106C15).

2023-10-07 07:46 UTC, TABASCOatw commented
Sure, np, just made the change.

2023-10-09 15:31 UTC, AP1400 requested changes
What should I do

2023-10-09 15:31 UTC, AP1400 commented on docs/tools/wallets/getting-started.md
> +| [Particle Network](https://particle.network) 	| non-custodial  | hybrid 	| no 	| yes 	| yes 	| yes 	| yes 	| mobile, browser, api/sdk 	|
Get back on metamask wallet

2023-10-10 03:01 UTC, TABASCOatw commented on docs/tools/wallets/getting-started.md
> +| [Particle Network](https://particle.network) 	| non-custodial  | hybrid 	| no 	| yes 	| yes 	| yes 	| yes 	| mobile, browser, api/sdk 	|
Hey @AP1400, I'm not entirely sure what you mean. Could you clarify?

2023-10-10 17:32 UTC, DannyS03 approved these changes

2023-10-10 17:33 UTC, merged