update(pos): tweaks to pol faqs
0xPolygon/wiki pull request #156
Opened 2023-10-14 03:53 UTC by DannyS03

Writing style tweaks and clarifications in faqs.

2023-10-14 13:11 UTC, cerberushades requested changes

2023-10-14 13:11 UTC, cerberushades commented on docs/pos/assets/pol.md
> +POL is native token upgrade for the Polygon ecosystem, designed for use in a wide range of activities and purposes, including as a tool for network participation and security. By staking POL, partici
```suggestion
POL is the native token upgrade for the Polygon ecosystem, designed for use in a wide range of activities and purposes, including as a tool for network participation and security. By staking POL, participants can actively contribute to the ecosystem as validators. Importantly, POL has many of the same features as MATIC, is built on OpenZeppelin's ERC20 implementations, and supports [<ins>EIP-2612</ins>](https://eips.ethereum.org/EIPS/eip-2612 for signature-based permit approvals.
```

2023-10-14 13:11 UTC, cerberushades commented on docs/pos/assets/pol.md
> +- **Bridging POL to Polygon PoS**: If you bridge POL tokens to Polygon PoS, you will receive
```suggestion
- **Bridging POL to Polygon PoS**: if you bridge POL tokens to Polygon PoS, you will receive 
```

2023-10-14 13:11 UTC, cerberushades commented on docs/pos/assets/pol.md
> +- **Bridging POL to Ethereum****: When bridging native tokens (POL), the bridge will always disburse POL tokens.
```suggestion
- **Bridging POL to Ethereum****: when bridging native tokens (POL), the bridge will always disburse POL tokens.
```

2023-10-14 13:11 UTC, cerberushades commented on docs/pos/assets/pol.md
> +The contracts are governed by the Polygon decentralized governance model. Changes can be proposed and voted on by the community via the PIP program. The contracts are governed by the Polygon decentra
```suggestion
The contracts are governed by the Polygon decentralized governance model. **In accordance with the PIP process, the community can propose changes and provide feedback.**
```

2023-10-16 07:23 UTC, EmpieichO approved these changes

2023-10-16 07:27 UTC, merged