Adding Crossmint on Polygon's PoS Docs under Deploy
0xPolygon/wiki pull request #184
Opened 2023-11-07 22:34 UTC by rohit-710

I work as a DevRel Engineer at Crossmint and I am trying to make a PR to include Crossmint on Polygon's Pos Docs under Deploy. 

Crossmint: http://crossmint.com/

Please review and merge accordingly. Please get back to me if there are any issues with this.

2023-11-08 22:05 UTC, rohit-710 commented
@cerberushades can you review this please?

2023-11-17 15:57 UTC, rohit-710 commented
Hey @cerberushades 
I think it would be nice to get the PR out for now, since I the rest of the deploy docs that I saw had a similar RMD structure. I am happy to help modify it to fit the new structure. 

Essentially we wanna get this merged so people can know that we exist and the tools we provide

2023-11-19 23:16 UTC, rohit-710 commented
Hey @cerberushades 
Any update here?

2023-11-20 13:29 UTC, cerberushades requested changes

2023-11-20 13:29 UTC, cerberushades commented on docs/pos/deploy/crossmint.md
> +  ![img](../../../static/img/Crossmint/screenshot1.jpg)
```suggestion
  ![img](/img/Crossmint/screenshot1.jpg)
```

This path should work. The same for the others.

2023-11-20 13:30 UTC, cerberushades commented
> Hey @cerberushades Any update here?

requestted a few more changes. I also dont see the update on sidebars.js.

2023-11-20 17:05 UTC, rohit-710 commented
Hey @cerberushades 
Thanks for the callout! I just updated those as well, let me know if there are any other changes that I may have missed

2023-11-20 17:42 UTC, cerberushades requested changes

2023-11-20 17:44 UTC, rohit-710 commented
@cerberushades, added!

2023-11-20 18:30 UTC, rohit-710 commented
I think it should work as expected now, apologies!

2023-11-20 19:35 UTC, cerberushades commented
> @cerberushades I think it should work as expected now, apologies!
I'll merge it now. A reminder, though: as I said previously, we're revamping the docs and still discussing if/how we'll be presenting 3rd party tutorials on the new docs. Stay tuned!

2023-11-20 19:35 UTC, merged