Update rpc-endpoints.md
0xPolygon/wiki pull request #26
Opened 2023-07-25 20:16 UTC by gaia

Removed MaticVigil and NOWNodes, both dead.

2023-07-26 09:30 UTC, ashucoder9 commented on docs/pos/reference/rpc-endpoints.md
> -* [NOWNodes](https://nownodes.io/nodes/polygon-matic)
Is this RPC provider really down? I can see their page and options to setup a Polygon node.

2023-07-26 09:30 UTC, ashucoder9 reviewed
Left a comment.

2023-07-26 15:27 UTC, gaia commented
Apologies, nownodes.io didn't resolve for me and I thought the domain was dead. Turns out it was the Pi-Hole DNS filtering (more specifically, [this list](https://github.com/NethServer/dns-community-blacklist/blob/master/firebog-crypto.dns#L12345))

2023-08-03 04:01 UTC, DannyS03 requested changes

2023-08-03 04:01 UTC, DannyS03 commented on docs/pos/reference/rpc-endpoints.md
> -* [NOWNodes](https://nownodes.io/nodes/polygon-matic)
```suggestion
* [NOWNodes](https://nownodes.io/nodes/polygon-matic)
```

2023-08-06 03:12 UTC, DannyS03 commented on docs/pos/reference/rpc-endpoints.md
> -* [NOWNodes](https://nownodes.io/nodes/polygon-matic)
```suggestion
* [NOWNodes](https://nownodes.io/nodes/polygon-matic)
```

2023-08-08 12:47 UTC, cerberushades commented
Hey @gaia, can you please edit the PR according to Danny's suggestion?

2023-08-08 13:42 UTC, gaia commented
all set? I've resolved the review

2023-08-09 03:53 UTC, DannyS03 commented
We don't need to remove NOWNodes @gaia

2023-08-28 15:43 UTC, closed without merging