revamps POS quick start
0xPolygon/wiki pull request #57
Opened 2023-08-16 18:45 UTC by cerberushades

- Reorganizes info
- Introduces Polygon 2.0 information
- Includes resources table
- Updates content

Points to be discussed:
- Adding a video right from the top, outlining the whole article
- Add comparison to zkevm
- Add links to specific tutorials provided by 3rd parties
- provide more resources (links to devrel content)
- POS safe current status.

2023-08-17 02:26 UTC, DannyS03 requested changes
Thanks for taking this, @cerberushades. I left a handful of suggestions.

- I suggest we revisit certain aspects of the issue to ensure alignment with the scope. If not, we should present an alternative solution.
- "POS" should be "PoS" throughout the document.
- Let's ensure to keep SEO in mind and the user's perspective - this is the motivation behind updating the headings to "How To's".

2023-08-28 20:31 UTC, cerberushades commented on docs/pos/quick-start.md
> +Driven toward the scalability of the Ethereum network, it aims at providing a low-cost blockchain service, with negligible fees compared to L1, and at the same time benefit from the Ethereum battle-t
I'll edit and move this to the very beginning of the article then

2023-09-01 15:58 UTC, cerberushades commented on docs/pos/quick-start.md
> +In our design, Ethereum provides smart contracts that support the validator community, such as the ones for staking MATIC and sending out rewards, as well as checkpoint contracts that sync the state
I thought I should be concise when talking about the architecture, since we got a whole article about it. I'll add a link to it then.

2023-09-06 21:56 UTC, rjfraize80 commented
Grear

2023-10-02 09:39 UTC, DannyS03 commented
Will be addressed in another change request as part of efforts to ramp up the PoS doc.

2023-10-02 09:39 UTC, closed without merging